### ISSUE TITLE
Get code for kernel.

### ISSUE THREAD

**Issue by manthanrtilva** [boundarydevices/linux-imx6#15]
Hi,

I have downloaded Image for Nitrogen Max board for Ubuntu, it works fine.
kernel version for it is as below.
root@nitrogen:~# uname -a
Linux nitrogen 3.10.53-15-boundary-7t5 #15 SMP PREEMPT Tue Jul 21 14:07:28 MST 2015 armv7l armv7l armv7l GNU/Linux
r

From where i can get source code for this kernel version.

Thanks in advance.

**Comment by gibsson** [comment]
Hi,

This is the right repository. If you are not sure about which kernel version to use, please refer to the blog post which offers the Ubuntu, the branch name is given there:
https://boundarydevices.com/ubuntu-trusty-for-i-mx6-boards-june-2015-kernel-3-10-53/
https://github.com/boundarydevices/linux-imx6/tree/boundary-imx_3.10.53_1.1.1_ga

Regards,
Gary
