### ISSUE TITLE
Build a new Kernel

### ISSUE THREAD

**Issue by asad-lesani** [boundarydevices/linux-imx6#20]
Hi,

I'm going to build a new Kernel for Ubuntu. I followd these steps:
I have downloaded the Kernel source file from `https://github.com/boundarydevices/linux-imx6.git`
Then coppied the `nitrogen6x_defconfig` to the main root of the source code as `.config`.
Then I run `make`. 
After a while I get this error:
```
  CC      lib/percpu_ida.o
make[1]: stat: lib/hash.c: File name too long
make[1]: *** No rule to make target `lib/hash.c', needed by `lib/hash.o'.  Stop.
make: *** [lib] Error 2
```

Can anyone help me to solve that and build my own image?

**Comment by tkisky** [comment]
On 7/6/2016 5:56 AM, asad-lesani wrote:
> Hi,
> 
> I'm going to build a new Kernel for Ubuntu. I followd these steps:
> I have downloaded the Kernel source file from |https://github.com/boundarydevices/linux-imx6.git|
> Then coppied the |nitrogen6x_defconfig| to the main root of the source code as |.config|.


Try "make nitrogen6x_defconfig" instead. The defconfig files are much smaller than the corresponding
.config

**Comment by asad-lesani** [comment]
Hi,

When I want to run `make nitrogen6x_defconfig` I get this error:
`can't find default configuration "arch/x86/configs/nitrogen6x_defconfig"` 
Should i copy nitrogen6x_defconfig in this directory: arch/x86/configs/nitrogen6x_defconfig

**Comment by iancoolidge89** [comment]
export ARCH=arm

**Comment by asad-lesani** [comment]
Not I could run the make, but I get this error:
`SVE15123CDW:~/Desktop/linux-imx6-boundary-imx_3.14.28_1.0.0_ga# make
scripts/kconfig/conf --silentoldconfig Kconfig
  CHK     include/config/kernel.release
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
make[1]: `include/generated/mach-types.h' is up to date.
  CC      kernel/bounds.s
gcc: error: unrecognized argument in option ‘-mabi=aapcs-linux’
gcc: note: valid arguments to ‘-mabi=’ are: ms sysv
gcc: error: unrecognized command line option ‘-mlittle-endian’
gcc: error: unrecognized command line option ‘-mapcs’
gcc: error: unrecognized command line option ‘-mno-sched-prolog’
gcc: error: unrecognized command line option ‘-mno-thumb-interwork’
gcc: error: unrecognized command line option ‘-mfpu=vfp’
make[1]: *** [kernel/bounds.s] Error 1
make: *** [prepare0] Error 2
`

**Comment by telelaci** [comment]
Read these posts first, it might help :
https://boundarydevices.com/cross-compiling-kernels-2014-edition-2/
https://boundarydevices.com/ubuntunizing-i-mx6-kernels/

**Comment by asad-lesani** [comment]
I tried to follow them, this is what I get after making:
drivers/media/v4l2-core/videobuf-dma-contig.o
make[3]: *** No rule to make target `drivers/media/v4l2-core/videobuf2-memops.c', needed by `drivers/media/v4l2-core/videobuf2-memops.o'.  Stop.
make[3]: *** Waiting for unfinished jobs....
  CC      drivers/media/v4l2-core/videobuf2-core.o
make[2]: *** [drivers/media/v4l2-core] Error 2
make[1]: *** [drivers/media] Error 2
make: *** [drivers] Error 2

**Comment by telelaci** [comment]
Hi Asad,
Please tell me exactly what have you done.
You can send it directly to me :
laci@boundarydevices.com
Regards,
Laci

**Comment by titusece** [comment]
Asad,
You can clean your kernel and build again.
make distclean ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf-
make nitrogen6x_defconfig ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf-
make uImage modules -j4 ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf-

I hope this helps,
