### ISSUE TITLE
Linux Kernel with real time patch

### ISSUE THREAD

**Issue by yzh89** [boundarydevices/linux-imx6#31]
I see for older version of linux kernel there is a RT patched branch. Can someone add a rt patched branch for 3.14.52_1.1.0_ga?

**Comment by gibsson** [comment]
Hi,
We have a Yocto recipe for PREEMPT_RT integration with our 4.1.15 kernel:
https://github.com/Freescale/meta-freescale-3rdparty/blob/master/recipes-kernel/linux/linux-boundary-rt_4.1.15.bb
Regards,
Gary
