### ISSUE TITLE
Can't sync time using hardware stamps

### ISSUE THREAD

**Issue by cobras** [boundarydevices/linux-imx6#37]
Hi, I wish to use PTP to sync device using the fec driver with kernel 2.10.17. 10.0.2_ga.
To do it, I'm using ptp version 1.8.
I'm using the following simple command :+1: 
 - For the master : ptp4l -i eth0 -l 7 -m
  - For the slave: ptp4l -i eth0 -s -l 7 -m
Below a trace of my slave one :
**# ptp4l -i eth0 -l 7 -m -s**
ptp4l[55950.439]: config item (null).assume_two_step is 0
ptp4l[55950.440]: config item (null).check_fup_sync is 0
ptp4l[55950.440]: config item (null).tx_timestamp_timeout is 1
ptp4l[55950.440]: config item (null).clock_servo is 0
ptp4l[55950.440]: config item (null).time_stamping is 1
ptp4l[55950.441]: config item (null).clock_servo is 0
ptp4l[55950.441]: config item (null).clockClass is 248
ptp4l[55950.441]: config item (null).clockAccuracy is 254
ptp4l[55950.441]: config item (null).offsetScaledLogVariance is 65535
ptp4l[55950.441]: config item (null).productDescription is ';;'
ptp4l[55950.442]: config item (null).revisionData is ';;'
ptp4l[55950.442]: config item (null).userDescription is ''
ptp4l[55950.442]: config item (null).manufacturerIdentity is '00:00:00'
ptp4l[55950.442]: config item (null).domainNumber is 0
ptp4l[55950.443]: config item (null).slaveOnly is 1
ptp4l[55950.443]: config item (null).twoStepFlag is 1
ptp4l[55950.443]: config item (null).priority1 is 128
ptp4l[55950.443]: config item (null).priority2 is 128
ptp4l[55950.443]: config item (null).gmCapable is 1
ptp4l[55950.443]: config item (null).gmCapable is 1
ptp4l[55950.444]: config item (null).free_running is 0
ptp4l[55950.444]: selected /dev/ptp0 as PTP clock
ptp4l[55950.444]: config item (null).uds_address is '/var/run/ptp4l'
ptp4l[55950.444]: section item /var/run/ptp4l.announceReceiptTimeout now 0
ptp4l[55950.444]: section item /var/run/ptp4l.delay_mechanism now 0
ptp4l[55950.445]: section item /var/run/ptp4l.network_transport now 0
ptp4l[55950.445]: section item /var/run/ptp4l.delay_filter_length now 1
ptp4l[55950.445]: config item (null).free_running is 0
ptp4l[55950.445]: config item (null).freq_est_interval is 1
ptp4l[55950.445]: config item (null).gmCapable is 1
ptp4l[55950.446]: config item (null).kernel_leap is 1
ptp4l[55950.446]: config item (null).utc_offset is 37
ptp4l[55950.446]: config item (null).timeSource is 160
ptp4l[55950.446]: config item (null).pi_proportional_const is 0.000000
ptp4l[55950.447]: config item (null).pi_integral_const is 0.000000
ptp4l[55950.447]: config item (null).pi_proportional_scale is 0.000000
ptp4l[55950.447]: config item (null).pi_proportional_exponent is -0.300000
ptp4l[55950.447]: config item (null).pi_proportional_norm_max is 0.700000
ptp4l[55950.447]: config item (null).pi_integral_scale is 0.000000
ptp4l[55950.448]: config item (null).pi_integral_exponent is 0.400000
ptp4l[55950.448]: config item (null).pi_integral_norm_max is 0.300000
ptp4l[55950.448]: config item (null).step_threshold is 0.000000
ptp4l[55950.448]: config item (null).first_step_threshold is 0.000020
ptp4l[55950.448]: config item (null).max_frequency is 900000000
ptp4l[55950.449]: config item (null).tsproc_mode is 0
ptp4l[55950.449]: config item (null).delay_filter is 1
ptp4l[55950.449]: config item (null).delay_filter_length is 10
ptp4l[55950.449]: config item (null).summary_interval is 0
ptp4l[55950.449]: config item (null).sanity_freq_limit is 200000000
ptp4l[55950.450]: PI servo: sync interval 1.000 kp 0.700 ki 0.300000
ptp4l[55950.450]: config item /var/run/ptp4l.boundary_clock_jbod is 0
ptp4l[55950.450]: config item /var/run/ptp4l.network_transport is 0
ptp4l[55950.451]: config item /var/run/ptp4l.delayAsymmetry is 0
ptp4l[55950.451]: config item /var/run/ptp4l.follow_up_info is 0
ptp4l[55950.451]: config item /var/run/ptp4l.freq_est_interval is 1
ptp4l[55950.451]: config item /var/run/ptp4l.hybrid_e2e is 0
ptp4l[55950.451]: config item /var/run/ptp4l.path_trace_enabled is 0
ptp4l[55950.452]: config item /var/run/ptp4l.ingressLatency is 0
ptp4l[55950.452]: config item /var/run/ptp4l.egressLatency is 0
ptp4l[55950.452]: config item /var/run/ptp4l.delay_mechanism is 0
ptp4l[55950.452]: config item /var/run/ptp4l.fault_badpeernet_interval is 16
ptp4l[55950.452]: config item /var/run/ptp4l.fault_reset_interval is 4
ptp4l[55950.452]: config item /var/run/ptp4l.tsproc_mode is 0
ptp4l[55950.453]: config item /var/run/ptp4l.delay_filter is 1
ptp4l[55950.453]: config item /var/run/ptp4l.delay_filter_length is 1
ptp4l[55950.453]: config item eth0.boundary_clock_jbod is 0
ptp4l[55950.453]: config item eth0.network_transport is 1
ptp4l[55950.453]: config item eth0.delayAsymmetry is 0
ptp4l[55950.787]: config item eth0.follow_up_info is 0
ptp4l[55950.787]: config item eth0.freq_est_interval is 1
ptp4l[55950.787]: config item eth0.hybrid_e2e is 0
ptp4l[55950.787]: config item eth0.path_trace_enabled is 0
ptp4l[55950.787]: config item eth0.ingressLatency is 0
ptp4l[55950.787]: config item eth0.egressLatency is 0
ptp4l[55950.787]: config item eth0.delay_mechanism is 1
ptp4l[55950.787]: config item eth0.fault_badpeernet_interval is 16
ptp4l[55950.788]: config item eth0.fault_reset_interval is 4
ptp4l[55950.788]: config item eth0.tsproc_mode is 0
ptp4l[55950.788]: config item eth0.delay_filter is 1
ptp4l[55950.788]: config item eth0.delay_filter_length is 10
ptp4l[55950.788]: config item eth0.logMinDelayReqInterval is 0
ptp4l[55950.788]: config item eth0.logAnnounceInterval is 1
ptp4l[55950.788]: config item eth0.announceReceiptTimeout is 3
ptp4l[55950.788]: config item eth0.syncReceiptTimeout is 0
ptp4l[55950.789]: config item eth0.transportSpecific is 0
ptp4l[55950.789]: config item eth0.logSyncInterval is 0
ptp4l[55950.789]: config item eth0.logMinPdelayReqInterval is 0
ptp4l[55950.789]: config item eth0.neighborPropDelayThresh is 20000000
ptp4l[55950.789]: config item eth0.min_neighbor_prop_delay is -20000000
ptp4l[55950.789]: config item eth0.udp_ttl is 1
ptp4l[55950.790]: driver changed our HWTSTAMP options
ptp4l[55950.791]: tx_type   1 not 1
ptp4l[55950.791]: rx_filter 1 not 12
ptp4l[55950.791]: config item (null).dscp_event is 0
ptp4l[55950.791]: config item (null).dscp_general is 0
ptp4l[55950.791]: port 1: INITIALIZING to LISTENING on INIT_COMPLETE
ptp4l[55950.791]: config item /var/run/ptp4l.logMinDelayReqInterval is 0
ptp4l[55950.792]: config item /var/run/ptp4l.logAnnounceInterval is 1
ptp4l[55950.792]: config item /var/run/ptp4l.announceReceiptTimeout is 0
ptp4l[55950.792]: config item /var/run/ptp4l.syncReceiptTimeout is 0
ptp4l[55950.792]: config item /var/run/ptp4l.transportSpecific is 0
ptp4l[55950.792]: config item /var/run/ptp4l.logSyncInterval is 0
ptp4l[55950.792]: config item /var/run/ptp4l.logMinPdelayReqInterval is 0
ptp4l[55950.792]: config item /var/run/ptp4l.neighborPropDelayThresh is 20000000
ptp4l[55950.793]: config item /var/run/ptp4l.min_neighbor_prop_delay is -20000000
ptp4l[55950.793]: config item (null).uds_address is '/var/run/ptp4l'
ptp4l[55950.793]: port 0: INITIALIZING to LISTENING on INIT_COMPLETE
ptp4l[55950.793]: interface index 1 is up
ptp4l[55950.794]: interface index 2 is up
ptp4l[55950.794]: port 1: link up
ptp4l[55950.794]: interface index 3 is down
ptp4l[55951.019]: port 0: setting asCapable
ptp4l[55954.357]: port 1: setting asCapable
ptp4l[55954.357]: port 1: new foreign master 0019b8.fffe.02774a-1
ptp4l[55958.121]: port 1: announce timeout
ptp4l[55958.122]: config item eth0.udp_ttl is 1
ptp4l[55958.123]: driver changed our HWTSTAMP options
ptp4l[55958.123]: tx_type   1 not 1
ptp4l[55958.123]: rx_filter 1 not 12
ptp4l[55958.123]: config item (null).dscp_event is 0
ptp4l[55958.123]: config item (null).dscp_general is 0
ptp4l[55958.123]: selected best master clock 0019b8.fffe.0277c1
ptp4l[55958.357]: selected best master clock 0019b8.fffe.02774a
ptp4l[55958.357]: port 1: LISTENING to UNCALIBRATED on RS_SLAVE
ptp4l[55959.398]: port 1: delay timeout
ptp4l[55959.399]: delay   filtered          0   raw          0
ptp4l[55960.357]: master offset 10668909788 s0 freq      +0 path delay         0
ptp4l[55960.603]: port 1: delay timeout
ptp4l[55960.604]: delay   filtered          0   raw          0
ptp4l[55961.358]: master offset 10668909788 s0 freq      +0 path delay         0
ptp4l[55962.358]: master offset 10668909788 s0 freq      +0 path delay         0
ptp4l[55962.495]: port 1: delay timeout
ptp4l[55962.496]: delay   filtered          0   raw          0

When I add -S to ptp (SOFTWARE STAMP), every things work right. But when I remove  -S, I can see raw and path delay not equal to zero.
Sep  1 02:27:20 ptp4l: [3959.206] port 1: delay timeout
Sep  1 02:27:20 ptp4l: [3959.207] delay   filtered      73190   raw      73999
Sep  1 02:27:20 ptp4l: [3959.827] master offset       4211 s2 freq   +6490 path delay     73190
Sep  1 02:27:20 ptp4l: [3959.880] port 1: delay timeout
Sep  1 02:27:20 ptp4l: [3959.881] delay   filtered      73190   raw      74690
ptp4l[3960.828]: master offset      14026 s2 freq   +7485 path delay     73190

In the packet capture, we can see precisionOriginTime is always the same with HARDWARE mode when it changes in SOFTWARE mode (See attached).
I have tried to merge commit to this driver using patches from other branch, but I never succeed to fix it.
Can you help me ?
Thanks in advance.
[ptp_18.zip](https://github.com/boundarydevices/linux-imx6/files/1073712/ptp_18.zip)

**Comment by gibsson** [comment]
Hi,

Can you please try with a newer kernel? It has changed quite a lot since 3.10.17:
https://github.com/boundarydevices/linux-imx6/tree/boundary-imx_4.1.15_2.0.0_ga

Regards,
Gary

**Comment by gibsson** [comment]
Hi,
Since there's no answer to our previous suggestion, we consider this issue fixed.
Regards,
Gary
