### ISSUE TITLE
iptables table 'mangle' does not exist

### ISSUE THREAD

**Issue by irfanka** [boundarydevices/linux-imx6#38]
Hi.

I'm trying to use the Nitrogen6Q_W board as a captive portal hotspot.
I'm using the "Ubuntu Xenial for i.MX boards (August 2016, kernel 4.1.15)" image that I got off of the BoundaryDevices website, and I've installed hostapd, coovachilli, and freeradius.

However, CoovaChilli is spewing this error when it tries to set up it's iptables rules:

`
iptables: No chain/target/match by that name.
iptables v1.6.0: can't initialize iptables table 'mangle': Table does not exist (do you need insmod?)
Perhaps iptables or your kernel needs to be upgraded.
`

I've also noticed that the 'nat' table is missing too.

Do I need to recompile the kernel to enable these?
Are they supported at all?
If so, do you have any hints which flags I should change during config?

Also, is it better if I use the kernel tree from the boundary-imx_4.1.15_2.0.0_ga branch, or should I stick with 1.0.0?

Thanks,

**Comment by gibsson** [comment]
Hi,

Iptables support was added to default configuration a few weeks ago.
https://github.com/boundarydevices/linux-imx6/commit/a5be86df

Are you sure your system is up to date?

Please apt update/upgrade, should work.

Regards,
Gary

**Comment by irfanka** [comment]
Well, I did already apt update/upgrade, but I still get the same error from coovachilli/iptables.

Do I need to modprobe something, maybe?

**Comment by irfanka** [comment]
I tried modprobe iptable_nat - and that worked, so the nat table is in fact now available.

However, the iptable_mangle module does not exist, and looking at [a5be86df](https://github.com/boundarydevices/linux-imx6/commit/a5be86df) I see that +CONFIG_NFT_NAT=m was added, put nothing related to MANGLE.

**Comment by irfanka** [comment]
Also, please don't close the issues so eagerly.

**Comment by gibsson** [comment]
Hi,

Sorry but I've closed the issue because this type of request is OS-related (not an issue per say) so we recommend using the blog post comments for that:
https://boundarydevices.com/ubuntu-xenial-mx67-boards-august-2016-kernel-4-1-15/

As for mangle, you can re-build the kernel with the option you need following this blog post:
https://boundarydevices.com/customizing-ubuntudebian-kernels/

Regards,
Gary

**Comment by irfanka** [comment]
OK, thanks.
