### ISSUE TITLE
help

### ISSUE THREAD

**Issue by vladut123** [boundarydevices/linux-imx6#43]
make -C router kernel -j`grep -c '^processor' /proc/cpuinfo`
make[1]
Makefile:15: config: No such file or directory
Makefile:57: *** empty variable name. Stop.
make[1]: 
Makefile:440: recipe for target 'kernel' failed
make: *** [kernel] Error 2

**Comment by gibsson** [comment]
Hi,

Please refer to our wiki on how to build this kernel:
https://boundarydevices.com/wiki/linux-kernel/#contentlink1

Regards
