### ISSUE TITLE
4.15

### ISSUE THREAD

**Issue by aep** [boundarydevices/linux-imx6#45]
4.9 is a bit old for us, any chance for at least 4.15?

**Comment by gibsson** [comment]
Hi,
If you want anything newer than what NXP offers, you need to use mainline kernel directly, most our boards are supported there already.
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
Regards,
Gary

**Comment by aep** [comment]
not with https://github.com/boundarydevices/buildroot-external-boundary

**Comment by gibsson** [comment]
Then that's a different discussion, about Buildroot. As far as the kernel is concerned, either use NXP fork or mainline.
