### ISSUE TITLE
Build of drivers/video/fbdev is broken

### ISSUE THREAD

**Issue by EdTott** [boundarydevices/linux-imx6#58]
A commit of include/dt-bindings/display/simple_panel_mipi_cmds.h_ on about 9th May 2020 has removed the definition of S_DCS_READ. This symbol is used in drivers/video/fbdev/mxc/mipi_dsi.c which will no longer compile.

**Comment by gibsson** [comment]
Hi, thanks for your feedback. We'll look into it.

**Comment by gibsson** [comment]
Hi,
Should be fixed now. Also know that we've added a CI server that checks both arm64 and arm32 now.
Thanks
