### ISSUE TITLE
[USB Camera Streaming Interface with iMX6Q SABRELITE]

### ISSUE THREAD

**Issue by Ash-S** [boundarydevices/linux-imx6#63]
Hi, I am trying to access USB camera connected with my iMX6Q SABRE Board. I am preferring to use gstreamer but stucked, how to use properly. I followed this tutorial...
https://boundarydevices.com/yocto-dunfell-release-for-i-mx6-i-mx7-platforms/ but doesnt work. 
Please help.

**Comment by gibsson** [comment]
Hi,
The procedure provided on this blog post is about MIPI-CSI camera.
For USB camera, you should use v4l2src GStreamer plugin.
If it doesn't work, please check your camera support in the mainline kernel. We know it works with UVC-compliant camera.
I'll close this issue as it is camera-specific, not a kernel bug.
Regards,
