### ISSUE TITLE
Errors when building the kernel

### ISSUE THREAD

**Issue by niusenc** [boundarydevices/linux-imx6#67]
Hello, I met some error messages when I was trying to build the kernel. The error messages are:
**drivers/video/fbdev/mxc/mipi_dsi_samsung.c:106:12: error: ‘struct mipi_dsi_info’ has no member named ‘lcd_callback’
drivers/video/fbdev/mxc/mipi_dsi_samsung.c:120:10: error: ‘struct mipi_dsi_info’ has no member named ‘lcd_callback’
drivers/video/fbdev/mxc/mipi_dsi_samsung.c:602:15: error: ‘struct mipi_dsi_info’ has no member named ‘lcd_inited’; did you mean ‘lcd_panel’?
drivers/video/fbdev/mxc/mipi_dsi_samsung.c:616:17: error: ‘struct mipi_dsi_info’ has no member named ‘lcd_callback’
drivers/video/fbdev/mxc/mipi_dsi_samsung.c:622:11: error: ‘struct mipi_dsi_info’ has no member named ‘lcd_inited’; did you mean ‘lcd_panel’?
drivers/video/fbdev/mxc/mipi_dsi_samsung.c:658:11: error: ‘struct mipi_dsi_info’ has no member named ‘lcd_inited’; did you mean ‘lcd_panel’?**

Any suggestions?

Thanks.

**Comment by tkisky** [comment]
Easiest is to remove CONFIG_FB_MXC_MIPI_DSI_SAMSUNG, or use boundary_defconfig
if you don't need the samsung display.
