### ISSUE TITLE
opengl segmentation fault on imx6q-sabresd board

### ISSUE THREAD

**Issue by bibikurosawa** [boundarydevices/linux-imx6#7]
Using the same file system (core-image-minimal + OpenGL support, + direct framebuffer) and Linux kernel 3.0.35 I can use the Vivante examples without any problem.

Examples are from gpu_sdk_v1.00.gz (available on Freescale site).

With this new kernel version (3.10.17_1.0.0 beta branch) I get a segmentation fault with both OpenGL and OpenCL examples.

**Comment by gibsson** [comment]
Hi,

This repository is for Boundary Devices platforms. Although the SabreSD platform should still work, we do not support, please refer to the NXP community website.

Regards,
Gary
